skip_tags: true

os: Visual Studio 2015

environment:
  matrix:
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"

build_script:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;;%PATH%"
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - "pip install -Ur test-requirements.txt"
  - "pip install codecov"

test_script:
  # -u makes sure we get prompt output
  - "python -u -m pytest -W error -ra async_generator -v -s --cov=async_generator --cov-config=.coveragerc"
  - "codecov"
